#!/usr/bin/env bash

SYSTEM_TYPE=$(uname -s)

#-----------------------------------------
# * Install brew packages and casks
#   https://yadm.io/docs/bootstrap
#-----------------------------------------

if [ "$SYSTEM_TYPE" = "Darwin" ]; then

  echo ">>> Installing brew packages.."
  brew bundle --file=~/.Brewfile-base

  if [[ ! -z "${BOOTSTRAP_LOCALAPP}" ]]; then
    export HOMEBREW_CASK_OPTS="--appdir=~/Applications"
  fi

  echo ">>> Install brew casks"
  brew bundle --file=~/.Brewfile-casks

  if [[ ! -z "${BOOTSTRAP_PERSO}" ]]; then
    echo ">>> Install brew casks (personal Applications)"
    brew bundle --file=~/.Brewfile-casks-perso
  fi

fi
