#!/usr/bin/env bash

SYSTEM_TYPE=$(uname -s)

# #TODO: Brewfiles (Homebrew bundle) support 'vscode' for extensions
# https://github.com/Homebrew/homebrew-bundle

#-----------------------------------------
# * Configure Visual Studio Code
#   (settings.json, keybindings.json, snippets/)
# * Intall Extensions
#-----------------------------------------

if [ "$SYSTEM_TYPE" = "Darwin" ]; then

    echo ">>> Setting Visual Studio Code user configs.."
    VSCODE_USERDIR="$HOME/Library/Application Support/Code/User"
    ln -sf $HOME/.vscode-conf/settings.json    "$VSCODE_USERDIR/settings.json"
    ln -sf $HOME/.vscode-conf/keybindings.json "$VSCODE_USERDIR/keybindings.json"
    ln -sf $HOME/.vscode-conf/snippets/        "$VSCODE_USERDIR/snippets"

fi

# Install extensions
echo ">>> Installing Visual Studio Code extensions.."
for ext in $(cat $HOME/.vscode-conf/vscode-extensions.txt); do
  code --install-extension "$ext"
done
