#!/usr/bin/env bash

SYSTEM_TYPE=$(uname -s)

#-----------------------------------------
# * Configure iTerm2 (to use ~/.iterm2/)
#   https://yadm.io/docs/bootstrap
#-----------------------------------------

if [ "$SYSTEM_TYPE" = "Darwin" ]; then

  if [ -d "$HOME/.iterm2" ]; then
    echo ">>> Setting iTerm prefs directory.."
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
  fi

fi
